BBBBBBB BBBBBB
BBBBB BBBB
    XXXXX XXXXXXXXBBB BBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXX
        XXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX
BBBBBBBB