BBBBBBB BBBBBB
BBBBB BBBB
    XXXXX XXXXXXXXBBB BBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXX
        XXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXXXXXXXXX
    XXXXXXX
BBBBBBBB