BBBBBBB BBBBBB
BBBBB BBBB
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXX
        XXXXXXXXX
        BB BBBBBBBBBBB
            XXXX XXXXXX XXXXXXXXXXXXX
        BBBBB
        XXX XXXXXXXXXXXXX XXXXXXX
            XXXXXXXXX
            XXXXXXXXX
            BB BBBBBBBBBBBBBXXXXXX XXXXXXXXXXBBBBB
            BB BBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXBBBBB
            BB BBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXXXXXXXX XXXXXXXXXXXXX
        XXXXX
    XXXXXX
BBBBBBBB