BBBBBBB BBBBBB
BBBBB BBBB
    XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX
    BB BBBBBBBB
        
    BBBBB
BBBBBBBB